### ISSUE TITLE
Add-In Assembly not found

### ISSUE THREAD

**Issue by dezindzer** [iRef3at/GenQ#1]
Getting this error when installing using [GenQ from Autodesk App Store](https://apps.autodesk.com/RVT/en/Detail/Index?id=6845680174115867006)
![image](https://user-images.githubusercontent.com/77564/189889748-18ec1e78-c9d8-423f-b3ed-801973843e02.png)

**Comment by iRef3at** [comment]
Hi,
You should not get such an error if u used the Autodesk installer. However,
you may try to uninstall GenQ via the same installer, and also uninstall
any previous versions, finally, make sure there are no GenQ-related
files/folders in your local Revit addins folder. before re-installing the
latest GenQ 1.0.1 via Autodesk installer again.

**Comment by dezindzer** [comment]
Restarting Revit resolved the issue.
